version: 0.0
os: linux
files:
  # Que archivos se copiaran en la instancia
  # https://docs.aws.amazon.com/codedeploy/latest/userguide/tutorials-on-premises-instance-2-create-sample-revision.html
  - source: ./docker-compose.production.yml
    # Carpeta donde lo vamos a dejar
    destination: /home/ubuntu/
  - source: scripts
    destination: /home/ubuntu/scripts

# Ciclo de vida del deployment 
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html
hooks:
  ApllicationStop:
    - location: ./scripts/application-stop.sh
      timeout: 10000
  AfterInstall:
    - location: ./scripts/after-install.sh
      timeout: 3000
  ApplicationStart:
    - location: ./scripts/application-start.sh
      timeout: 3000
  ValidateService:
    - location: ./scripts/validate-service.sh
      timeout: 3000